github.com:
    users:
        fractal27:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: fractal27
