# calc
# Autogenerated from man page /usr/share/man/man1/calc.1.gz
complete -c calc -s c -d 'Continue reading command lines even after a scan/parse error has caused the a…'
complete -c calc -s C -d 'Permit the execution of custom builtin functions'
complete -c calc -s d -d 'Disable the printing of the opening title'
complete -c calc -s D -d 'Force the initial value of config("calc_debug"), config("resource_debug") and…'
complete -c calc -s e -d 'Ignore any environment variables on startup'
complete -c calc -s f -d 'This flag is normally only with calc shell scripts'
complete -c calc -s h -d 'Print a help message.   This option implies  -q '
complete -c calc -s i -d 'Become interactive if possible'
complete -c calc -s m -d 'This flag sets the permission mode of  calc '
complete -c calc -s O -d 'Use the old classic defaults instead of the default configuration'
complete -c calc -s p -d 'Pipe processing is enabled by use of  -p .  For example: . sp 1 . in +5n '
complete -c calc -s q -d 'Disable the reading of the startup scripts'
complete -c calc -s s -d 'By default, all  calc_cmd args are evaluated and executed'
complete -c calc -s u -d 'Disable buffering of stdin and stdout'
complete -c calc -s v -d 'Print the  calc version number and exit'
complete -c calc -s n -d 'to setup a modified form of the default calc configuration.  The'

