# gh-alias-delete
# Autogenerated from man page /usr/share/man/man1/gh-alias-delete.1.gz
complete -c gh-alias-delete -l all -d 'Delete all aliases EXIT CODES 0: Successful execution 1: Error 2: Command can…'

