# gh-cache-delete
# Autogenerated from man page /usr/share/man/man1/gh-cache-delete.1.gz
complete -c gh-cache-delete -s a -l all -d 'Delete all caches OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-cache-delete -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXIT CODES 0: Su…'

