# gh-ruleset
# Autogenerated from man page /usr/share/man/man1/gh-ruleset.1.gz
complete -c gh-ruleset -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format ALIASES gh rs EX…'

