# gh-repo-archive
# Autogenerated from man page /usr/share/man/man1/gh-repo-archive.1.gz
complete -c gh-repo-archive -s y -l yes -d 'Skip the confirmation prompt EXIT CODES 0: Successful execution 1: Error 2: C…'

